import { Category } from '../categories/entities/category.entity';

export const categoriesSeed: Partial<Category>[] = [
  {
    name: 'Elektrikçi',
    description: 'Elektrik tesisatı, arıza giderme, bakım onarım',
    icon: '⚡',
    orderIndex: 1,
    parentId: null,
  },
  {
    name: 'Sıhhi Tesisatçı',
    description: 'Su tesisatı, kanalizasyon, ısıtma sistemleri',
    icon: '🚰',
    orderIndex: 2,
    parentId: null,
  },
  {
    name: 'Taksici',
    description: 'Şehir içi ve şehirler arası ulaşım',
    icon: '🚕',
    orderIndex: 3,
    parentId: null,
  },
  {
    name: 'Temizlikçi',
    description: 'Ev ve ofis temizliği, genel temizlik hizmetleri',
    icon: '🧹',
    orderIndex: 4,
    parentId: null,
  },
  {
    name: 'Bakıcı',
    description: 'Çocuk, yaşlı ve hasta bakımı',
    icon: '👶',
    orderIndex: 5,
    parentId: null,
  },
  {
    name: 'Bahçıvan',
    description: 'Bahçe bakımı, çim biçme, ağaç budama',
    icon: '🌱',
    orderIndex: 6,
    parentId: null,
  },
  {
    name: 'Tesisatçı',
    description: 'Doğalgaz, su, ısıtma tesisatı',
    icon: '🔧',
    orderIndex: 7,
    parentId: null,
  },
  {
    name: 'Boya Badana',
    description: 'İç ve dış cephe boya, badana işleri',
    icon: '🎨',
    orderIndex: 8,
    parentId: null,
  },
  {
    name: 'Marangoz',
    description: 'Ahşap işleri, mobilya yapımı ve tamiri',
    icon: '🪚',
    orderIndex: 9,
    parentId: null,
  },
  {
    name: 'Çilingir',
    description: 'Kilit açma, anahtar yapımı',
    icon: '🔑',
    orderIndex: 10,
    parentId: null,
  },
  {
    name: 'Klima Teknisyeni',
    description: 'Klima montaj, bakım, onarım',
    icon: '❄️',
    orderIndex: 11,
    parentId: null,
  },
  {
    name: 'Asansör Teknisyeni',
    description: 'Asansör bakım, onarım, montaj',
    icon: '🛗',
    orderIndex: 12,
    parentId: null,
  },
  {
    name: 'Çatı Ustası',
    description: 'Çatı yapımı, onarımı, izolasyon',
    icon: '🏠',
    orderIndex: 13,
    parentId: null,
  },
  {
    name: 'Seramikçi',
    description: 'Seramik, fayans döşeme işleri',
    icon: '🧱',
    orderIndex: 14,
    parentId: null,
  },
  {
    name: 'Demirci',
    description: 'Demir işleri, kaynak, metal işleme',
    icon: '🔨',
    orderIndex: 15,
    parentId: null,
  },
]; 